# Write your MySQL query statement below
SELECT T.EMPLOYEE_ID FROM (
    SELECT E.EMPLOYEE_ID, NAME, SALARY FROM EMPLOYEES AS E LEFT JOIN SALARIES AS S ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
     UNION
    SELECT S.EMPLOYEE_ID, NAME, SALARY FROM EMPLOYEES AS E RIGHT JOIN SALARIES AS S ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
) AS T WHERE T.SALARY IS NULL OR T.NAME IS NULL ORDER BY T.EMPLOYEE_ID ASC;